#apiVersion: v1
#kind: Pod
#metadata:
#  name: tanzu-image
#spec:
#  containers:
#  - name: tanzu-image
#    image: harbor.tanzu.bekind.io/demoapps/tanzu-image:latest
#    args:
#    - sleep
#    - "1000000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-shell
  labels:
    app: tanzu-shell
spec:
  selector:
    matchLabels:
      app: tanzu-shell
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: tanzu-shell
    spec:
      volumes:
      - name: acmefit-catalog-data
        emptyDir: {}
      containers:
      - image: harbor.tanzu.bekind.io/demoapps/tanzu-shell:latest
        imagePullPolicy: "Always"
        name: tanzu
        args:
        - sleep
        - "1000000"
